name: Build & Publish Docker image

on: [push, pull_request]
  paths:
    - 'centos-base'
    - 'centos-nginx'
    - 'centos-nginx-php-fpm'

jobs:
  docker-build:
    name: Build & Test Docker image
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Create Docker tag
        id: docker_image_tag
        if: success()
        run: echo ::set-output name=TAG::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Build :latest Docker images
        if: success()
        run: tests/scripts/00_docker_build.sh
