name: Docker image

on: [push, pull_request]

jobs:
  docker-build:
    name: Build & Test Docker image
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - name: Create Docker tag
        id: docker_image_tag
        if: success()
        run: echo ::set-output name=TAG::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with: 
          platforms: arm64, riscv64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push base service
        uses: docker/build-push-action@v4
        with:
          context: ./opensuse-leap-base/
          push: true
          tags: ghcr.io/perlur/opensuse-leap-base:latest
      - name: Build and push nginx service
        uses: docker/build-push-action@v4
        with:
          context: ./opensuse-leap-nginx/
          push: true
          tags: ghcr.io/perlur/opensuse-leap-nginx:latest
      - name: Build and push nginx and PHP FPM service
        uses: docker/build-push-action@v4
        with:
          context: ./opensuse-leap-nginx-php-fpm/
          push: true
          tags: ghcr.io/perlur/opensuse-leap-nginx-php-fpm:latest