name: Build & Publish Docker images

on: [push, pull_request]

jobs:
  docker-build:
    name: Build & Test Docker image

  strategy:
    matrix:
      images:
        - 'centos-base'
        - 'centos-nginx'
        - 'centos-nginx-php-fpm'
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Create Docker tag
        id: docker_image_tag
        if: success()
        run: echo ::set-output name=TAG::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Build :latest Docker images
        if: success()
        run: tests/scripts/00_docker_build.sh
